set_property PACKAGE_PIN Y9 [get_ports clk]
set_property PACKAGE_PIN P16 [get_ports rst]
set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports rst]

create_clock -period 10.000 -name CLK -waveform {0.000 5.000} -add [get_ports -filter { NAME =~  "*clk*" && DIRECTION == "IN" }]

set_property PACKAGE_PIN H17 [get_ports sw6]
set_property PACKAGE_PIN M15 [get_ports sw7]
set_property PACKAGE_PIN F22 [get_ports sw0]
set_property PACKAGE_PIN G22 [get_ports sw1]
set_property PACKAGE_PIN H22 [get_ports sw2]
set_property PACKAGE_PIN F21 [get_ports sw3]
set_property PACKAGE_PIN H19 [get_ports sw4]
set_property PACKAGE_PIN H18 [get_ports sw5]
set_property IOSTANDARD LVCMOS33 [get_ports sw6]
set_property IOSTANDARD LVCMOS33 [get_ports sw7]
set_property IOSTANDARD LVCMOS33 [get_ports sw0]
set_property IOSTANDARD LVCMOS33 [get_ports sw1]
set_property IOSTANDARD LVCMOS33 [get_ports sw2]
set_property IOSTANDARD LVCMOS33 [get_ports sw3]
set_property IOSTANDARD LVCMOS33 [get_ports sw4]
set_property IOSTANDARD LVCMOS33 [get_ports sw5]

set_property IOSTANDARD LVCMOS33 [get_ports led7]
set_property IOSTANDARD LVCMOS33 [get_ports led0]
set_property IOSTANDARD LVCMOS33 [get_ports led1]
set_property IOSTANDARD LVCMOS33 [get_ports led2]
set_property IOSTANDARD LVCMOS33 [get_ports led3]
set_property IOSTANDARD LVCMOS33 [get_ports led4]
set_property IOSTANDARD LVCMOS33 [get_ports led5]
set_property IOSTANDARD LVCMOS33 [get_ports led6]
set_property PACKAGE_PIN T22 [get_ports led0]
set_property PACKAGE_PIN T21 [get_ports led1]
set_property PACKAGE_PIN U22 [get_ports led2]
set_property PACKAGE_PIN U21 [get_ports led3]
set_property PACKAGE_PIN V22 [get_ports led4]
set_property PACKAGE_PIN W22 [get_ports led5]
set_property PACKAGE_PIN U19 [get_ports led6]
set_property PACKAGE_PIN U14 [get_ports led7]
