webtalk_init -webtalk_dir C:\\Users\\Chance\\Documents\\ece527\\demo_1\\demo_1.sdk\\webtalk
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "2017-09-11 15:50:56" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "SDK v2017.2" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2017.2" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "amd64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "SDK" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "false" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "n9v0d570c4qiqlosjvql77gv33" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "2017.2_2" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "2" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-4500U CPU @ 1.80GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2394 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.000 GB" -context "user_environment"
webtalk_register_client -client sdk
webtalk_add_data -client sdk -key uid -value "1505156076740" -context "sdk\\\\application/1505156076740"
webtalk_add_data -client sdk -key hwid -value "1505070293255" -context "sdk\\\\application/1505156076740"
webtalk_add_data -client sdk -key bspid -value "1505070325691" -context "sdk\\\\application/1505156076740"
webtalk_add_data -client sdk -key newbsp -value "false" -context "sdk\\\\application/1505156076740"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\application/1505156076740"
webtalk_add_data -client sdk -key apptemplate -value "hello_world" -context "sdk\\\\application/1505156076740"
webtalk_add_data -client sdk -key RecordType -value "APPCreation" -context "sdk\\\\application/1505156076740"
webtalk_add_data -client sdk -key LangUsed -value "C" -context "sdk\\\\application/1505156076740"
webtalk_add_data -client sdk -key Procused -value "ps7_cortexa9" -context "sdk\\\\application/1505156076740"
webtalk_add_data -client sdk -key uid -value "NA" -context "sdk\\\\bsp/1505163056194"
webtalk_add_data -client sdk -key RecordType -value "ToolUsage" -context "sdk\\\\bsp/1505163056194"
webtalk_add_data -client sdk -key BootgenCount -value "0" -context "sdk\\\\bsp/1505163056194"
webtalk_add_data -client sdk -key DebugCount -value "0" -context "sdk\\\\bsp/1505163056194"
webtalk_add_data -client sdk -key PerfCount -value "0" -context "sdk\\\\bsp/1505163056194"
webtalk_add_data -client sdk -key FlashCount -value "0" -context "sdk\\\\bsp/1505163056194"
webtalk_add_data -client sdk -key CrossTriggCount -value "0" -context "sdk\\\\bsp/1505163056194"
webtalk_add_data -client sdk -key QemuDebugCount -value "0" -context "sdk\\\\bsp/1505163056194"
webtalk_transmit -clientid 1801860411 -regid "" -xml C:\\Users\\Chance\\Documents\\ece527\\demo_1\\demo_1.sdk\\webtalk\\usage_statistics_ext_sdk.xml -html C:\\Users\\Chance\\Documents\\ece527\\demo_1\\demo_1.sdk\\webtalk\\usage_statistics_ext_sdk.html -wdm C:\\Users\\Chance\\Documents\\ece527\\demo_1\\demo_1.sdk\\webtalk\\sdk_webtalk.wdm -intro "<H3>SDK Usage Report</H3><BR>"
webtalk_terminate
